apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xvfwvvdmk-go 
  janus-idp.io/tekton: xvfwvvdmk-go
  backstage.io/kubernetes-id: xvfwvvdmk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xvfwvvdmk-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml